---

- name: Remove Existing ACI Tenant
  hosts: apic
  connection: local
  gather_facts: False
  
  vars: 
    tenant: "{{ input_tenant }}"
    vrf: "{{ input_vrf }}"
  tasks:
   - name: Removing Tenant Object
     aci_tenant:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"

   - name: Removing Application Profile Object
     aci_ap:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"
       ap: "{{ item }}"
     with_items:
       - ansible_app-ap

   - name: Removing VRF Object
     aci_vrf:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"
       vrf: "{{ vrf }}"
       description: "{{ vrf }}"

   - name: Removing Bridge Domain Object 
     aci_bd:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"
       bd: "{{ item }}"
     with_items:
       - "ansible_app-bd"
       
# create 2 subnets tie to bridge domain
   - name: Removing Tenant Subnets
     aci_bd_subnet:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"
       bd: "{{ item.bd }}"
       gateway: "{{ item.gateway }}"
       mask: "{{ item.mask }} "
       scope: "{{ item.scope }}"
     with_items:
       - { bd: "ansible_app-bd", gateway: "10.1.1.1", mask: "24", scope: public}
       - { bd: "ansible_app-bd", gateway: "10.1.2.1", mask: "24", scope: public}

   - name: Removing EPG Objects
     aci_epg:
       host: "{{ inventory_hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       state: "absent"
       validate_certs: False
       tenant: "{{ tenant }}"
       bd: "{{ item.bd }}"
       epg: "{{ item.epg}}"
       ap: "{{ item.ap }}"
       description : app EPG test with ansible use case
     with_items:
       - { bd: "ansible_app-bd", ap: "ansible_app-ap", epg: "ansible_app-epg"}
