---

- name: Failover FW1 ISP Traffic
  hosts: ASA_LAB
  gather_facts: false
  tags: [secondary]

  collections:
    - cisco.asa

  tasks:

    - name: Shutdown FW1 WAN Link
      cisco.asa.asa_config:
        lines:
          - shutdown
        parents: interface GigabitEthernet0/0
      when: "'ASA_LAB' in group_names"

- name: Failover FW1 and PE1 Traffic
  hosts: ISP_CONN
  gather_facts: false
  tags: [terciary]

  #collections:
  #  - cisco.asa

  tasks:

    - name: Shutdown FW1 WAN Link
      cisco.asa.asa_config:
        lines:
          - shutdown
        parents: interface GigabitEthernet0/0
      when: "'ASA_LAB' in group_names"

    - name: Shutdown PE1 Backhaul
      cisco.ios.ios_config:
        lines:
          - shutdown
        parents: interface Ethernet0/2
      when: "'NAT_PE1' in group_names"

- name: Restore all ISP Traffic
  hosts: ISP_CONN
  gather_facts: false
  tags: [allpaths]
  tasks:

  #collections:
  #  - cisco.asa

    - name: Restore FW1 WAN Link
      cisco.asa.asa_config:
        lines:
          - no shutdown
        parents: interface GigabitEthernet0/0
      when: "'ASA_LAB' in group_names"

    - name: Restore PE1 Backhaul
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: interface Ethernet0/2
      when: "'NAT_PE1' in group_names"
