---
- name: Configure L3 interfaces
  hosts: VxLAN-LAB 
  gather_facts: no
  tasks:
    - name: Import JSON data for NX Loopback interfaces config
      ansible.builtin.set_fact:
        interface_data: "{{ lookup('file', 'interface_data.json') | from_json }}"
    - name: Configure L3 interfaces on NXs
      cisco.nxos.nxos_config:
        lines:
          #Take into account that configuring an ip address on a non L3 interfaces will result in error
          - "ip address {{ item.ip }}"
          - "description {{ item.description }}"
        parents: "interface {{ item.interface }}"
      with_items: "{{ interface_data.'%s' }}"

