---
- name: Archive Device Configurations
  hosts: 1841_IOS
  gather_facts: no
  tasks:
    - name: Gather Device Configuration
      cisco.ios.ios_command:
        commands: show run
      register: device_config
    - name: Save Per Device Configuration to TXT
      ansible.builtin.copy:
        content: "{{ device_config.stdout[0] }}"
        dest: "./1841_ios_configs/{{ inventory_hostname }}_device_config.txt"
      delegate_to: localhost

