---
- name: Enable and Disable SCP on Nexus Switches
  hosts: NX-LEAF-1
  tasks:
    - name: Display Facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Enable SCP on LEAF1
      cisco.nxos.nxos_feature:
        feature: scp-server
    - name: Disable SCP on LEAF1
      cisco.nxos.nxos_feature:
        feature: scp-server
        state: disabled

